all : clean main

clean: 
	rm -f  *.o

snake: mySnake.o \
       Screen.o \
	   Snake.o \
	   SnakeNode.o \
	   timeval.o \
	   LivingArea.o \
	   Block.o

	g++ -o snake mySnake.o Screen.o Snake.o SnakeNode.o timeval.o LivingArea.o Block.o 

mySnake.o:mySnake.c 
